title: Emad Elsaid
description: A Software Engineer
baseurl: ""
url: https://www.emadelsaid.com
meta_description: A Software Engineer
domain_name: https://www.emadelsaid.com
author: Emad Elsaid
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-optional-front-matter

exclude:
  - .git
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

defaults:
    - scope:
        type: pages
      values:
        layout: default
    - scope:
        type: posts
      values:
        layout: post

# Jekyll SEO tag
twitter:
  username: emad__elsaid
logo: /images/avatar.webp
social:
  name: Emad Elsaid
  links:
    - https://www.github.com/emad-elsaid
    - https://www.twitter.com/emad__elsaid
    - https://www.facebook.com/emad.elsaid.hamed
    - https://www.youtube.com/EmadElsaid
    - https://www.linkedin.com/in/emadelsaid
    - https://www.twitch.tv/internalerr
    - https://www.keybase.io/emadelsaid
