title: Emad Elsaid
description: Ruby/Go Web Developer
baseurl: ""
url: "https://www.emadelsaid.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-optional-front-matter

exclude:
  - .git
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

name: Emad Elsaid
meta_description: Ruby/Go Web Developer
aboutPage: true

domain_name: 'https://www.emadelsaid.com'
author:         'Emad Elsaid'
authorTwitter:  'emad__elsaid'

permalink:       /:title/
defaults:
    - scope:
        type: pages
      values:
        layout: default
    - scope:
        type: posts
      values:
        layout: post
