baseURL = "http://www.emadelsaid.com/"
languageCode = "en-us"
title = "Emad Elsaid"
theme = "cactus"
publishDir = "../"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-112396214-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = ""
paginate = 20

[params]
	name = "Emad Elsaid"
	description = "Ruby/Go Web Developer"
	bio = "Ruby/Go Web Developer"
	# Enter optionally your twitter account
	twitter = "emad__elsaid"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ["css/custom_style.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "All Articles"
	subscribe = "RSS"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Software Engineer, Ruby/Go Web Developer"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "rounded"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/emad__elsaid"
    facebook = "https://www.facebook.com/emad.elsaid.hamed"
    github   = "https://www.github.com/emad-elsaid"
