name: Xlog

on:
  push:
    branches: [ "migrating-to-xlog" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt install -y libc6 libc-bin
          ./xlog \
          --build . \
          --sitename "Emad Elsaid"

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: .
